# Generated by Django 2.2.19 on 2024-03-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveSmallIntegerField()),
                ('value', models.FloatField()),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Peace',
        ),
        migrations.AddField(
            model_name='country_rating',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_rating', to='ratings.Country'),
        ),
        migrations.AddField(
            model_name='country_rating',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_rating', to='ratings.Rating'),
        ),
        migrations.AddConstraint(
            model_name='country_rating',
            constraint=models.UniqueConstraint(fields=('country', 'rating', 'year'), name='unique_country_rating_year'),
        ),
    ]
