# Generated by Django 2.2.19 on 2024-01-31 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Democracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('value', models.FloatField()),
                ('year', models.PositiveSmallIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='democracy', to='ratings.Country')),
            ],
        ),
        migrations.AddConstraint(
            model_name='democracy',
            constraint=models.UniqueConstraint(fields=('country', 'year'), name='unique_country_year'),
        ),
    ]
