# Generated by Django 2.2.19 on 2024-03-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20240314_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
