# Generated by Django 2.2.19 on 2024-03-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20240314_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country_rating',
            name='place',
        ),
    ]
