# Generated by Django 2.2.19 on 2024-03-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_remove_country_rating_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='decreasing',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
